config/routes.rb
Rails.application.routes.draw do

  root 'root#index'

  resources :volunteers
  resources :organizations do
    resources :opportunities
  end

  post '/volunteers/:id/final' => 'volunteers#final', as: :final_volunteer
  get '/volunteers/:id/final' => 'volunteers#final'
  get '/volunteers/:id/options' => 'volunteers#options', as: :volunteer_options
  patch '/volunteers/:id/options' => 'volunteers#options'
  get '/auth/:provider/callback', to: 'sessions#create'

  delete '/sessions', to: 'sessions#destroy', as: 'logout'

end

app/models/availability.rb
class Availability < ActiveRecord::Base
end

app/models/need.rb
class Need < ActiveRecord::Base
  belongs_to :opportunity
  belongs_to :skill

end

app/models/opportunity.rb
class Opportunity < ActiveRecord::Base
  has_many :needs
  has_many :skills, through: :needs
  has_many :volunteers
  belongs_to :organization

  validates :organization_id, presence: true
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :opportunities
  has_many :needs, through: :opportunities

  validates :uid, :uniqueness => {:scope => :provider}

  def self.find_or_create_from_auth_hash(auth_hash)
    find_by_omniauth(auth_hash) || create_with_omniauth(auth_hash)
  end

  def self.create_with_omniauth(auth_hash)
    create(
            :uid      => auth_hash[:uid],
            :provider => auth_hash[:provider],
            :name     => auth_hash[:info][:name],
            :photo    => auth_hash[:info][:image]
          )
  end

  def self.find_by_omniauth(auth_hash)
    find_by(uid: auth_hash[:uid], provider: auth_hash[:provider] )
  end
end

app/models/proficiency.rb
class Proficiency < ActiveRecord::Base
  belongs_to :skill
  belongs_to :volunteer
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :needs
  has_many :proficiencies
end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
  has_many :proficiencies
  has_many :skills, :through => :proficiencies
  has_one :opportunity

  validates :uid, :uniqueness => {:scope => :provider}


  def self.find_or_create_from_auth_hash(auth_hash)
    find_by_omniauth(auth_hash) || create_with_omniauth(auth_hash)
  end

  def self.create_with_omniauth(auth_hash)

    create(
            :uid      => auth_hash[:uid],
            :provider => auth_hash[:provider],
            :name     => auth_hash[:info][:name],
            :photo    => auth_hash[:info][:image]
          )
  end

  def self.find_by_omniauth(auth_hash)
    find_by(uid: auth_hash[:uid], provider: auth_hash[:provider] )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private

    def login(user, type)
      if type == "volunteer"
        session[:volunteer_id] = user.id
      elsif type == "organization"
        session[:organization_id] = user.id
      end
    end

    def logged_in?
      !!current_user
    end

    def current_user
      User.find(session[:volunteer_id]) if session[:volunteer_id]
    end


    helper_method :logged_in?, :current_user, :login
end

app/controllers/opportunities_controller.rb
class OpportunitiesController < ApplicationController
  def index
    @organization = Organization.find(params[:organization_id])
  end

  def new
    @organization = Organization.find(params[:organization_id])
    @opportunity = Opportunity.new
  end

  def edit
  end

  def create
    org = Organization.find(params[:organization_id])
    org.opportunities.build(opportunity_params)
    org.save

    redirect_to organization_opportunities_path(org)
  end

  def update
    @volunteer = Volunteer.find(sessions[:id])
  end

  def destroy
  end

  private
    def opportunity_params
      params.require(:opportunity).permit(:name, :datetime, :skill_ids => [])
    end

    def skill_params
      params.require(:opportunity).permit(:skill_ids => [])
    end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  def new
    @organization = Organization.new
    session[:is_organization] = true

    redirect_to '/auth/facebook'
  end

  def index
    @organizations = Organization.all
  end

  def show
    @organization = Organization.find(params[:id])
  end

  def create
  end

  def edit
  end

  def destroy
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

 def create
  if session[:is_organization] == false
    user = Volunteer.find_or_create_from_auth_hash(self.auth_hash)
    login(user, "volunteer")
      redirect_to volunteer_path(user)    
  else
    user = Organization.find_or_create_from_auth_hash(self.auth_hash)
    login(user, "organization")
    redirect_to organization_opportunities_path(user)
  end
end

  def destroy
    reset_session
    redirect_to root_path
  end 

  protected
    def auth_hash
      request.env['omniauth.auth']
    end
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  def new
    @volunteer = Volunteer.new
    session[:is_organization] = false

    redirect_to '/auth/facebook'
  end

  def index
    @volunteers = Volunteer.all
  end

  def create
    @volunteer = Volunteer.new(volunteer_params)
    redirect_to edit_volunteer_path(@volunteer) if @volunteer.save
  end

  def edit
    @volunteer = Volunteer.find(session[:volunteer_id])
  end

  def options
    @volunteer = Volunteer.find(session[:volunteer_id])
    @volunteer.update(volunteer_params)
    @opportunities = Opportunity.all
    @matches = get_matching_opportunities(@volunteer, @opportunities)

    case @matches.size
    when 3
      @columns = 4
    when 2
      @columns = 6
    else 
      @columns = 12
    end
  end

  def show
    @volunteer = Volunteer.find(session[:volunteer_id])
    #@volunteer = Volunteer.find(params[:id])
  end

  def final
    @volunteer = Volunteer.find(session[:volunteer_id])
    @opportunity = Opportunity.find(params[:opportunity_id])
    @opportunity.volunteer_id = @volunteer.id
    @volunteer.opportunity = @opportunity
    @volunteer.save
    @opportunity.save
  end

  def get_matching_opportunities(volunteer, opportunities)
    matching_opportunities = []    
    opportunities.each do |opportunity|
      if volunteer_skill_is_needed(volunteer, opportunity) && volunteer_is_available(volunteer, opportunity)
        matching_opportunities << opportunity
      end
    end
    return matching_opportunities[0..2]
  end

  def volunteer_is_available(volunteer, opportunity)
    volunteer.datetime == opportunity.datetime
  end

  def volunteer_skill_is_needed(volunteer, opportunity)
    volunteer.skills.find { |s| opportunity.skills.include?(s) }
  end

  private
    def volunteer_params
      params.require(:volunteer).permit(:name, :location, :datetime, :skill_ids => [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/opportunities_helper.rb
module OpportunitiesHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer" style="background-image: url('<%= image_path('bg-footer.jpg') %>')">
    <div class="container text-center">
        <div class="row">
             <div class="col-md-4 contact-details">
                <h4><i class="fa fa-phone"></i> Call</h4>
                <p>347-994-1313</p>
            </div>
            <div class="col-md-4 contact-details">
                <h4><i class="fa fa-map-marker"></i> Visit</h4>
                <p>11 Broadway<br>New York, NY 10010</p>
            </div>
            <div class="col-md-4 contact-details">
                <h4><i class="fa fa-envelope"></i> Email</h4>
                <p><a href="mailto:mail@example.com">pitch.in@flatironschool.com</a>
                </p>
            </div>
        </div>
        <div class="row social">
            <div class="col-lg-12">
                <ul class="list-inline">
                    <li><a href="#"><i class="fa fa-facebook fa-fw fa-2x"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-twitter fa-fw fa-2x"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-linkedin fa-fw fa-2x"></i></a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row copyright">
            <div class="col-lg-12">
                <p class="small">&copy; 2014 Pitch In</p>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
<meta name="description" content="">
<meta name="author" content="">

<title>Pitch In</title>

<!-- Default Fonts -->
<link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Raleway:400,100,200,300,600,500,700,800,900' rel='stylesheet' type='text/css'>

<!-- IE8 support for HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
<![endif]-->

app/views/layouts/_nav.html.erb
<!-- Navigation -->
<!-- Note: navbar-default and navbar-inverse are both supported with this theme. -->
<nav class="navbar navbar-inverse navbar-fixed-top navbar-expanded">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#page-top">
                <%= image_tag("hands_lg.png", class: "img-responsive", alt:"PitchIn") %>
             </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li>
                    <a href="#about">About</a>
                </li>
                <li>
                    <a href="#team">Team</a>
                </li>
                <li>
                    <a href="#contact">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Master</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/header' %>
</head>
<body id="page-top">
<%= render 'layouts/nav' %>

<%= yield %>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/opportunities/create.html.erb
<h1>Opportunities#create</h1>
<p>Find me in app/views/opportunities/create.html.erb</p>

app/views/opportunities/destroy.html.erb
<h1>Opportunities#destroy</h1>
<p>Find me in app/views/opportunities/destroy.html.erb</p>

app/views/opportunities/edit.html.erb
<h1>Opportunities#edit</h1>
<p>Find me in app/views/opportunities/edit.html.erb</p>

app/views/opportunities/index.html.erb
<h1>Organization Name: <%= @organization.name %></h1>

These are all your opportunities:
<ul>
  <% @organization.opportunities.each do |o| %>
    <li><%= o.name %> on <%= o.datetime.strftime("%B %d, %Y")  %></li>
    <% end %>
</ul>

<button><%= link_to "Add New Opportunity", new_organization_opportunity_path(@organization) %></button>

app/views/opportunities/new.html.erb
<h1>Opportunities#new</h1>

<%= form_for @opportunity, url: {action: "create"} do |f| %>
<%= f.label "Name of Opportunity", :name %>
<%= f.text_field :name %><br>

<%= f.label "What date is your event?" %><br>
  <% Date.today.upto(Date.today.next_day(6)).each do |day| %>
    <%= radio_button "opportunity", "datetime", day %><%= day.strftime("%B %d, %Y") %><br>
  <% end %>

  <%= f.label "What skills do you need? " %><br>
  <%= f.collection_check_boxes :skill_ids, Skill.all, :id, :name %><br>
<%= f.submit %>
<% end %>

app/views/opportunities/update.html.erb
<h1>Opportunities#update</h1>
<p>Find me in app/views/opportunities/update.html.erb</p>

app/views/organizations/_center.html.erb
<div class="container-fluid" style="margin-top:120px">
  <div class="row text-center">
    <div class="col-lg-12 wow fadeIn">

app/views/organizations/_center_close.html.erb
    </div>
  </div>
</div>

app/views/organizations/create.html.erb
<h1>Organizations#create</h1>
<p>Find me in app/views/organizations/create.html.erb</p>

app/views/organizations/destroy.html.erb
<h1>Organizations#destroy</h1>
<p>Find me in app/views/organizations/destroy.html.erb</p>

app/views/organizations/edit.html.erb
<h1>Organizations#edit</h1>
<p>Find me in app/views/organizations/edit.html.erb</p>

app/views/organizations/index.html.erb
<h1>Organizations#index</h1>
<p>Find me in app/views/organizations/index.html.erb</p>

app/views/organizations/new.html.erb
<h1>Organizations#new</h1>
<p>Find me in app/views/organizations/new.html.erb</p>

app/views/organizations/show.html.erb
<h1 style="margin-top:120px">Organization Name: <%= @organization.name %></h1>
 <%= image_tag @organization.photo %>
 <div style="width:100%" >
<div style="margin-left:35%">
<h3>These are all your opportunities:</h3>
<ul>
  <% @organization.opportunities.each do |o| %>
    <li><%= o.name %> on <%= o.datetime.strftime("%B %d, %Y")  %></li>
    <% end %>
</ul>
<div style="margin-left:10%">
<button style="margin-bottom: 15px"><%= link_to "Add New Opportunity", new_organization_opportunity_path(@organization) %></button>
</div>
</div>
</div>

app/views/root/index.html.erb
    <header style="background-image: url('<%= image_path('volunteer_bg.jpg') %>')">
        <div class="intro-content">

        <!--<%= image_tag("hands.png", class: "img-responsive img-centered") %> -->


            <div class="brand-name">WANT TO PITCH IN?</div>
            <hr class="colored">
            <button type="submit" class="btn btn-outline-light" id="volunteer"><a href="/volunteers/new">Login with Facebook</a></button>
            <button type="submit" class="btn btn-outline-light" id="organization"><a href="/organizations/new">Do You Need Volunteers?</a></button>
        </div>
        <div class="scroll-down">
            <a class="btn" href="#about"><i class="fa fa-angle-down fa-fw"></i></a>
        </div>
    </header>

    <section id="about">
        <div class="container-fluid">
            <div class="row text-center">
                <div class="col-lg-12 wow fadeIn">
                    <h1>Make a difference today</h1>
                    <p>PitchIn makes it easy for charity organizations to find motivated volunteers.</p>
                    <hr class="colored">
                </div>
            </div>
            <div class="row text-center content-row">
                <div class="col-md-3 col-sm-6 wow fadeIn" data-wow-delay=".2s">
                    <div class="about-content">
                        <i class="fa fa-eye fa-4x"></i>
                        <h3>Time Sensitive</h3>
                        <p>Our unique time-domain restricted scheduling platform matches organizations with volunteers with real-time results.</p>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 wow fadeIn" data-wow-delay=".4s">
                    <div class="about-content">
                        <i class="fa fa-edit fa-4x"></i>
                        <h3>Easy to Use</h3>
                        <p>PitchIn features an intuitive interface making it simple for both parties to get intended results.</p>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 wow fadeIn" data-wow-delay=".6s">
                    <div class="about-content">
                        <i class="fa fa-tablet fa-4x"></i>
                        <h3>Responsive</h3>
                        <p>Our multi-platform web app is optimized for mobile, desktop, and more environments.</p>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 wow fadeIn" data-wow-delay=".8s">
                    <div class="about-content">
                        <i class="fa fa-heart fa-4x"></i>
                        <h3>Built with Love</h3>
                        <p>PitchIn was built by three compassionate developers, eager to make a difference in the world.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
    <section id="team" class="bg-gray">
        <div class="container text-center wow fadeIn" style="visibility: visible; -webkit-animation: fadeIn;">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Our Team</h2>
                    <hr class="colored">
                </div>
                <div class="row content-row">
                    <div class="col-lg-12">
                        <div class="about-carousel owl-carousel owl-theme" style="opacity: 1; display: block;">
                            <div class="owl-wrapper-outer">
                                <div class="owl-wrapper" style="width: 3800px; left: 0px; display: block;">
                                    <div class="owl-item" style="width: 380px;">
                                        <div class="item">
                                            <%= image_tag("people/1.jpg", class: "img-responsive") %>
                                            <div class="caption">
                                                <h3>Tom Cohenno</h3>
                                                <hr class="colored">
                                                <p>Frontend Engineer</p>
                                                <ul class="list-inline social">
                                                    <li>
                                                        <a href="#"><i class="fa fa-facebook fa-fw"></i></a>
                                                    </li>
                                                    <li>
                                                        <a href="#"><i class="fa fa-twitter fa-fw"></i></a>
                                                    </li>
                                                    <li>
                                                        <a href="#"><i class="fa fa-linkedin fa-fw"></i></a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="owl-item" style="width: 380px;">
                                        <div class="item">
                                            <%= image_tag("people/2.jpg", class: "img-responsive") %>
                                            <div class="caption">
                                                <h3>Draisy Sabel</h3>
                                                <hr class="colored">
                                                <p>Backend Engineer</p>
                                                <ul class="list-inline social">
                                                    <li>
                                                        <a href="#"><i class="fa fa-facebook fa-fw"></i></a>
                                                    </li>
                                                    <li>
                                                        <a href="#"><i class="fa fa-twitter fa-fw"></i></a>
                                                    </li>
                                                    <li>
                                                        <a href="#"><i class="fa fa-linkedin fa-fw"></i></a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="owl-item" style="width: 380px;">
                                        <div class="item">
                                            <%= image_tag("people/3.jpg", class: "img-responsive") %>
                                            <div class="caption">
                                                <h3>Sam Van Train</h3>
                                                <hr class="colored">
                                                <p>Full Stack Engineer</p>
                                                <ul class="list-inline social">
                                                    <li>
                                                        <a href="#"><i class="fa fa-facebook fa-fw"></i></a>
                                                    </li>
                                                    <li>
                                                        <a href="#"><i class="fa fa-twitter fa-fw"></i></a>
                                                    </li>
                                                    <li>
                                                        <a href="#"><i class="fa fa-linkedin fa-fw"></i></a>
                                                    </li>
                                                    <li>
                                                        <a href="#"><i class="fa fa-dribbble fa-fw"></i></a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div> 
            </div>
        </div>
    </section>
    <aside class="cta-quote" style="background-image: url('<%= image_path('bg-aside.jpg') %>')">
        <div class="container wow fadeIn">
            <div class="row">
                <div class="col-md-10 col-md-offset-1">
                    <span class="quote">We <span class="text-primary">make a living</span> by what we get, but <span class="text-primary">we make a life</span> by what we <span class="text-primary">give</span>.</span>
                    <hr class=" colored">
                    <%= link_to 'Go Volunteer', new_volunteer_path, class: "btn btn-outline-light" %>
                </div>
            </div>
        </div>
    </aside>


    <section id="contact">
        <div class="container wow fadeIn">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Contact Us</h2>
                    <hr class="colored">
                    <p>Have a suggestion or want to help? Get in touch and let us know.</p>
                </div>
            </div>
            <div class="row content-row">
                <div class="col-lg-8 col-lg-offset-2">
                    <form name="sentMessage" id="contactForm" novalidate>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <label>Name</label>
                                <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <label>Email Address</label>
                                <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <label>Phone Number</label>
                                <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <label>Message</label>
                                <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <br>
                        <div id="success"></div>
                        <div class="row">
                            <div class="form-group col-xs-12">
                                <button type="submit" class="btn btn-outline-dark">Send</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

    <footer class="footer" style="background-image: url('assets/img/bg-footer.jpg')">
        <div class="container text-center">
            <div class="row">
                <div class="col-md-4 contact-details">
                    <h4><i class="fa fa-phone"></i> Call</h4>
                    <p>555-213-4567</p>
                </div>
                <div class="col-md-4 contact-details">
                    <h4><i class="fa fa-map-marker"></i> Visit</h4>
                    <p>3481 Melrose Place<br>Beverly Hills, CA 90210</p>
                </div>
                <div class="col-md-4 contact-details">
                    <h4><i class="fa fa-envelope"></i> Email</h4>
                    <p><a href="mailto:mail@example.com">mail@example.com</a>
                    </p>
                </div>
            </div>
            <div class="row social">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li><a href="#"><i class="fa fa-facebook fa-fw fa-2x"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-twitter fa-fw fa-2x"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-linkedin fa-fw fa-2x"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="row copyright">
                <div class="col-lg-12">
                    <p class="small">&copy; 2014 Start Bootstrap Themes</p>
                </div>
            </div>
        </div>
    </footer>

    

app/views/volunteers/final.html.erb
<div class="container-fluid">
  <div class="row text-center">
    <div class="col-lg-12 wow fadeIn">
     <h1>Great!</h1>
     <p>Thanks for signing up to the event: <strong><%= @opportunity.name %> on <%= @opportunity.datetime.strftime("%B %d, %Y") %></strong>.</p>
     <p>We look forward to seeing you there. Thank you for making the world a better place.</p>
     <hr class="colored">
    </div> 
  </div>
</div>

 

app/views/volunteers/index.html.erb
 
<% @volunteers.each do |volunteer| %>

<div class="owl-item" style="width: 380px;">
  <div class="item">
  <!-- <img src="assets/img/people/1.jpg" class="img-responsive" alt=""> -->
  <div class="caption">
      <h3><%= volunteer.name %></h3>
      <hr class="colored">
      <ul class="list-inline social">
          <li>
              <a href="#"><i class="fa fa-facebook fa-fw"></i></a>
          </li>
          <li>
              <a href="#"><i class="fa fa-twitter fa-fw"></i></a>
          </li>
          <li>
              <a href="#"><i class="fa fa-linkedin fa-fw"></i></a>
          </li>
      </ul>
  </div>
  </div>
</div>

<% end %>

app/views/volunteers/new.html.erb
<%= form_for @volunteer do |f| %>
<%= f.text_field :name %>
<%= f.submit %>
<% end %>

app/views/volunteers/show.html.erb
<%= render 'center' %>
<div style="width:30%; margin:0 auto;">
  <h3 style="float:left">Hi <%= @volunteer.name %></h3>
  <%= image_tag @volunteer.photo %>
</div>
<br/><br/>

  <% if @volunteer.opportunity != nil %>
  <div class="show-text">
    <p>Currently, you signed up for <strong><%= @volunteer.opportunity.name %></strong> on <strong><%= @volunteer.opportunity.datetime.strftime("%B %d, %Y") %></strong>.</p>
    <p>If you would like to sign up for a different event, please edit the details below:</p>
  </div>

  <% else %>
  <div class="show-text">
    <p>Currently, you have not signed up for any volunteer opportunities. Please answer the following three questions and we'll show you a list of available opportunities to choose from!</p>
  </div>
  <% end %>

    <%= form_for @volunteer, :style => "text-align:center;", :url => volunteer_options_path(@volunteer) do |f| %>
          <div class="col-md-12 col-sm-6 wow fadeIn" data-wow-delay=".2s">
            <%= f.label "Where would you like to help?" %><br>
            <% ["Queens", "Brooklyn", "Manhattan", "Bronx", "Staten Island"].each do |borough| %>
              <div style="margin-right:5px; display:inline-block">
                <%= radio_button "volunteer", "location", borough %><%= borough %>
              </div>
          <% end %>
          </div>

      <div class="col-md-12 col-sm-6 wow fadeIn" data-wow-delay=".2s">
      <br>
      <%= f.label "When would you like to help?" %><br>
      <% Date.today.upto(Date.today.next_day(6)).each do |day| %>
        <%= radio_button "volunteer", "datetime", day %><%= day.strftime("%B %d, %Y") %><br>
      <% end %>
      </div>
        
      <div class="col-md-12 col-sm-6 wow fadeIn" data-wow-delay=".2s">
      <br/>
      <%= f.label "What skills do you have?" %><br>
      <%= f.collection_check_boxes :skill_ids, Skill.all, :id, :name %>
      <br><br>
      <%= f.submit "Update Details" %>
      <br/><br/>
      </div>
  <% end %>
<%= render 'center_close' %>